### ISSUE TITLE
Publish non-jsx files

### ISSUE THREAD

**Issue by beaucollins** [Automattic/genericons-neue-react#3]
This project contains `.jsx` so requires a babel transform step for any project that uses it. Commonly, tools like webpack are configured to ignore source files in `node_modules`.

Should we also provide vanilla js versions of the icons in this project?

For instance, usually the webpack loader for babel is configured like this:

```js
{ test: /\.jsx?$/, exclude: /node_modules/, loaders: [ 'babel-loader' ] },
```

However, if this project is installed as a dependency, the source files will not be transformed from the jsx to a browser compatible version unless the `exclude` is modified:

```js
{ test: /\.jsx?$/, exclude: /node_modules\/(?!genericons-neue-react)/, loaders: [ 'babel-loader' ] },
```

**Comment by mkaz** [comment]
Is there a way to convert each icon individually to vanilla js? 

My initial attempts ended up creating a single bundle with all icons. Ideally you can use just one icon and not need to require all.

**Comment by beaucollins** [comment]
Yeah, using the `--out-dir` (`-d`) option with `babel`.

```
babel --out-dir output/directory src/
```

**Comment by mkaz** [comment]
Ah, this might be ideal setup, what I initially wanted. Then babel and everything can just be dev dependencies.

**Comment by beaucollins** [comment]
I can update my pr (#1) to publish the transpiled js.

**Comment by beaucollins** [comment]
I think `react` should also be a `peerDependency` and the version constraint can be loosened.
